############################################################
# +------------------------------------------------------+ #
# |                 PickupMoney                          | #
# |                 Configuration                        | #   
# +------------------------------------------------------+ #
############################################################


# Options to chance the behaviour
options: {}
  
messages: {}
  
#Blacklist worlds
#Money will not drop in these worlds.  
blacklisted_worlds:
 - world2
  
#  
# These are the materials/icons that will be dropped for a range of money.
# A valid list of materials can be found on spigot's documentation: 
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
# 
icon:
  '1':
    material: GOLD_NUGGET
    rangeMin: 1
    rangeMax: 10
  '2':
    material: GOLD_INGOT
    rangeMin: 10
    rangeMax: 50
  '3':
    material: GOLD_BLOCK
    rangeMin: 50
    rangeMax: 100
  '4':
    material: EMERALD
    rangeMin: 100
    rangeMax: 300

    
# These are the entities that can drop money.
# You can specify a minimum and maximum amount and a chance to drop money
entity:
  SHEEP:
    enabled: true
    amount: 8-12
    chance: 50.55
  PIG:
    enabled: true
    amount: 8-12
    chance: 50.55
  ELDER_GUARDIAN:
    enabled: true
    amount: 8-12
    chance: 50.55
  WITHER_SKELETON:
    enabled: true
    amount: 8-12
    chance: 50.55
  STRAY:
    enabled: true
    amount: 8-12
    chance: 50.55
  WITHER_SKULL:
    enabled: true
    amount: 8-12
    chance: 50.55
  HUSK:
    enabled: true
    amount: 8-12
    chance: 50.55
  ZOMBIE_VILLAGER:
    enabled: true
    amount: 8-12
    chance: 50.55
  SKELETON_HORSE:
    enabled: true
    amount: 8-12
    chance: 50.55
  ZOMBIE_HORSE:
    enabled: true
    amount: 8-12
    chance: 50.55
  DONKEY:
    enabled: true
    amount: 8-12
    chance: 50.55
  MULE:
    enabled: true
    amount: 8-12
    chance: 50.55
  EVOKER:
    enabled: true
    amount: 8-12
    chance: 50.55
  VEX:
    enabled: true
    amount: 8-12
    chance: 50.55
  VINDICATOR:
    enabled: true
    amount: 8-12
    chance: 50.55
  ILLUSIONER:
    enabled: true
    amount: 8-12
    chance: 50.55
  CREEPER:
    enabled: true
    amount: 8-12
    chance: 50.55
  SKELETON:
    enabled: true
    amount: 8-12
    chance: 50.55
  SPIDER:
    enabled: true
    amount: 8-12
    chance: 50.55
  GIANT:
    enabled: true
    amount: 8-12
    chance: 50.55
  ZOMBIE:
    enabled: true
    amount: 8-12
    chance: 50.55
  SLIME:
    enabled: true
    amount: 8-12
    chance: 50.55
  GHAST:
    enabled: true
    amount: 8-12
    chance: 50.55
  PIG_ZOMBIE:
    enabled: true
    amount: 8-12
    chance: 50.55
  ENDERMAN:
    enabled: true
    amount: 8-12
    chance: 50.55
  CAVE_SPIDER:
    enabled: true
    amount: 8-12
    chance: 50.55
  SILVERFISH:
    enabled: true
    amount: 8-12
    chance: 50.55
  BLAZE:
    enabled: true
    amount: 8-12
    chance: 50.55
  MAGMA_CUBE:
    enabled: true
    amount: 8-12
    chance: 50.55
  ENDER_DRAGON:
    enabled: true
    amount: 8-12
    chance: 50.55
  WITHER:
    enabled: true
    amount: 8-12
    chance: 50.55
  BAT:
    enabled: true
    amount: 8-12
    chance: 50.55
  WITCH:
    enabled: true
    amount: 8-12
    chance: 50.55
  ENDERMITE:
    enabled: true
    amount: 8-12
    chance: 50.55
  GUARDIAN:
    enabled: true
    amount: 8-12
    chance: 50.55
  SHULKER:
    enabled: true
    amount: 8-12
    chance: 50.55
  COW:
    enabled: true
    amount: 8-12
    chance: 50.55
  CHICKEN:
    enabled: true
    amount: 8-12
    chance: 50.55
  SQUID:
    enabled: true
    amount: 8-12
    chance: 50.55
  WOLF:
    enabled: true
    amount: 8-12
    chance: 50.55
  MUSHROOM_COW:
    enabled: true
    amount: 8-12
    chance: 50.55
  SNOWMAN:
    enabled: true
    amount: 8-12
    chance: 50.55
  OCELOT:
    enabled: true
    amount: 8-12
    chance: 50.55
  IRON_GOLEM:
    enabled: true
    amount: 8-12
    chance: 50.55
  HORSE:
    enabled: true
    amount: 8-12
    chance: 50.55
  RABBIT:
    enabled: true
    amount: 8-12
    chance: 50.55
  POLAR_BEAR:
    enabled: true
    amount: 8-12
    chance: 50.55
  LLAMA:
    enabled: true
    amount: 8-12
    chance: 50.55
  PARROT:
    enabled: true
    amount: 8-12
    chance: 50.55
  VILLAGER:
    enabled: true
    amount: 8-12
    chance: 50.55
  TURTLE:
    enabled: true
    amount: 8-12
    chance: 50.55
  PHANTOM:
    enabled: true
    amount: 8-12
    chance: 50.55
  COD:
    enabled: true
    amount: 8-12
    chance: 50.55
  SALMON:
    enabled: true
    amount: 8-12
    chance: 50.55
  PUFFERFISH:
    enabled: true
    amount: 8-12
    chance: 50.55
  TROPICAL_FISH:
    enabled: true
    amount: 8-12
    chance: 50.55
  DROWNED:
    enabled: true
    amount: 8-12
    chance: 50.55
  DOLPHIN:
    enabled: true
    amount: 8-12
    chance: 50.55