############################################################
# +------------------------------------------------------+ #
# |                 PickupMoney                          | #
# |                 Configuration                        | #   
# +------------------------------------------------------+ #
############################################################


# Options to chance the behaviour
Options: {}

Messages: {}

#Blacklist worlds
#Money will not drop in these worlds.  
Blacklist:
  - world2

#  
# These are the materials/icons that will be dropped for a range of money.
# A valid list of materials can be found on spigot's documentation: 
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
# 
Icon:
  '1':
    Material: GOLD_NUGGET
    Range: 1-10
  '2':
    Material: GOLD_INGOT
    Range: 10-50
  '3':
    Material: GOLD_BLOCK
    Range: 50-100
  '4':
    Material: EMERALD
    Range: 100-300

# These are the entities that can drop money.
# You can specify a minimum and maximum amount and a chance to drop money
Entity:
  SHEEP:
    Amount: 8-12
    Chance: 50.55
  PIG:
    Amount: 8-12
    Chance: 50.55
  ELDER_GUARDIAN:
    Amount: 8-12
    Chance: 50.55
  WITHER_SKELETON:
    Amount: 8-12
    Chance: 50.55
  STRAY:
    Amount: 8-12
    Chance: 50.55
  WITHER_SKULL:
    Amount: 8-12
    Chance: 50.55
  HUSK:
    Amount: 8-12
    Chance: 50.55
  ZOMBIE_VILLAGER:
    Amount: 8-12
    Chance: 50.55
  SKELETON_HORSE:
    Amount: 8-12
    Chance: 50.55
  ZOMBIE_HORSE:
    Amount: 8-12
    Chance: 50.55
  DONKEY:
    Amount: 8-12
    Chance: 50.55
  MULE:
    Amount: 8-12
    Chance: 50.55
  EVOKER:
    Amount: 8-12
    Chance: 50.55
  VEX:
    Amount: 8-12
    Chance: 50.55
  VINDICATOR:
    Amount: 8-12
    Chance: 50.55
  ILLUSIONER:
    Amount: 8-12
    Chance: 50.55
  CREEPER:
    Amount: 8-12
    Chance: 50.55
  SKELETON:
    Amount: 8-12
    Chance: 50.55
  SPIDER:
    Amount: 8-12
    Chance: 50.55
  GIANT:
    Amount: 8-12
    Chance: 50.55
  ZOMBIE:
    Amount: 8-12
    Chance: 50.55
  SLIME:
    Amount: 8-12
    Chance: 50.55
  GHAST:
    Amount: 8-12
    Chance: 50.55
  PIG_ZOMBIE:
    Amount: 8-12
    Chance: 50.55
  ENDERMAN:
    Amount: 8-12
    Chance: 50.55
  CAVE_SPIDER:
    Amount: 8-12
    Chance: 50.55
  SILVERFISH:
    Amount: 8-12
    Chance: 50.55
  BLAZE:
    Amount: 8-12
    Chance: 50.55
  MAGMA_CUBE:
    Amount: 8-12
    Chance: 50.55
  ENDER_DRAGON:
    Amount: 8-12
    Chance: 50.55
  WITHER:
    Amount: 8-12
    Chance: 50.55
  BAT:
    Amount: 8-12
    Chance: 50.55
  WITCH:
    Amount: 8-12
    Chance: 50.55
  ENDERMITE:
    Amount: 8-12
    Chance: 50.55
  GUARDIAN:
    Amount: 8-12
    Chance: 50.55
  SHULKER:
    Amount: 8-12
    Chance: 50.55
  COW:
    Amount: 8-12
    Chance: 50.55
  CHICKEN:
    Amount: 8-12
    Chance: 50.55
  SQUID:
    Amount: 8-12
    Chance: 50.55
  WOLF:
    Amount: 8-12
    Chance: 50.55
  MUSHROOM_COW:
    Amount: 8-12
    Chance: 50.55
  SNOWMAN:
    Amount: 8-12
    Chance: 50.55
  OCELOT:
    Amount: 8-12
    Chance: 50.55
  IRON_GOLEM:
    Amount: 8-12
    Chance: 50.55
  HORSE:
    Amount: 8-12
    Chance: 50.55
  RABBIT:
    Amount: 8-12
    Chance: 50.55
  POLAR_BEAR:
    Amount: 8-12
    Chance: 50.55
  LLAMA:
    Amount: 8-12
    Chance: 50.55
  PARROT:
    Amount: 8-12
    Chance: 50.55
  VILLAGER:
    Amount: 8-12
    Chance: 50.55
  TURTLE:
    Amount: 8-12
    Chance: 50.55
  PHANTOM:
    Amount: 8-12
    Chance: 50.55
  COD:
    Amount: 8-12
    Chance: 50.55
  SALMON:
    Amount: 8-12
    Chance: 50.55
  PUFFERFISH:
    Amount: 8-12
    Chance: 50.55
  TROPICAL_FISH:
    Amount: 8-12
    Chance: 50.55
  DROWNED:
    Amount: 8-12
    Chance: 50.55
  DOLPHIN:
    Amount: 8-12
    Chance: 50.55