name: MoneyDrops
main: net.crytec.pickmoney.PickupMoney
version: ${project.version}
authors: [crysis992]
depend: [Vault]
api-version: 1.14

commands:
  moneydrop:
    permission: pickupmoney.admin
    description: Basic Administration Commands for this Plugin.
    usage: "Use /moneydrop reload or /moneydrop drop <amount>"